spring.application.name=MyNG

# ================= DATABASE =================
spring.config.import=file:./src/main/resources/credentials.properties

spring.datasource.url=jdbc:mysql://localhost:3306/myngdb?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ================= JPA / HIBERNATE =================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect